### ISSUE TITLE
Add stuff

### ISSUE THREAD

**Issue by proprdev** [proprdev/joe#1]
* Hide Stuff in the Status Bar
* Legacy Dock Background (solid background)
* iPad Style Dock(?)
* Hide Good Morning and Good Night View from Bedtime
* Hide Do Not Disturb Notification

**Comment by isaiahangnakak** [comment]
Change the colour of the battery icon for different states?

**Comment by proprdev** [comment]
> Change the colour of the battery icon for different states?
That's not what joe is designed to be, it's designed to be an alternative to Lynx or Springtomize. Good idea, just doesn't fix this tweak.

**Comment by proprdev** [comment]
Legacy Dock Background probably in [SBDockView.h](https://developer.limneos.net/index.php?ios=14.4&framework=SpringBoardHome.framework&header=SBDockView.h)

**Comment by proprdev** [comment]
i dont use this
